add condition
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

diff --git a/.github/workflows/path-test.yaml b/.github/workflows/path-test.yaml
--- a/.github/workflows/path-test.yaml
+++ b/.github/workflows/path-test.yaml
@@ -55,6 +55,7 @@ jobs:
     needs: [update-to-date, setup-go, install-dependencies, check-version]
     if: always()
     steps:
-      - name: Passed
+      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
         run: |
-          echo "Passed"
+          echo "Some jobs failed or were cancelled."
+          exit 1
